package com.egceo.app.myfarm.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.egceo.app.myfarm.db.SendComment;
import com.egceo.app.myfarm.db.SendResource;

import com.egceo.app.myfarm.db.SendCommentDao;
import com.egceo.app.myfarm.db.SendResourceDao;
import com.egceo.app.myfarm.db.UserProfileDao;
import com.egceo.app.myfarm.entity.UserProfile;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sendCommentDaoConfig;
    private final DaoConfig sendResourceDaoConfig;
    private final DaoConfig userProfileDaoConfig;

    private final SendCommentDao sendCommentDao;
    private final SendResourceDao sendResourceDao;
    private final UserProfileDao userProfileDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sendCommentDaoConfig = daoConfigMap.get(SendCommentDao.class).clone();
        sendCommentDaoConfig.initIdentityScope(type);

        sendResourceDaoConfig = daoConfigMap.get(SendResourceDao.class).clone();
        sendResourceDaoConfig.initIdentityScope(type);

        userProfileDaoConfig = daoConfigMap.get(UserProfileDao.class).clone();
        userProfileDaoConfig.initIdentityScope(type);

        sendCommentDao = new SendCommentDao(sendCommentDaoConfig, this);
        sendResourceDao = new SendResourceDao(sendResourceDaoConfig, this);
        userProfileDao = new UserProfileDao(userProfileDaoConfig, this);

        registerDao(SendComment.class, sendCommentDao);
        registerDao(SendResource.class, sendResourceDao);
        registerDao(UserProfile.class, userProfileDao);
    }
    
    public void clear() {
        sendCommentDaoConfig.getIdentityScope().clear();
        sendResourceDaoConfig.getIdentityScope().clear();
        userProfileDaoConfig.getIdentityScope().clear();
    }

    public SendCommentDao getSendCommentDao() {
        return sendCommentDao;
    }

    public SendResourceDao getSendResourceDao() {
        return sendResourceDao;
    }

    public UserProfileDao getUserProfileDao() {
        return userProfileDao;
    }

}
