package com.egceo.app.myfarm.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SEND_RESOURCE".
 */
public class SendResource {

    private Integer resourceId;
    private String resourceName;
    private String resourceType;
    private String resourceLocation;
    private String resourceProperty;
    private Integer referrenceObjectId;
    private String isDeleted;
    private String createdBy;
    private java.util.Date createdTime;
    private String updatedBy;
    private java.util.Date updatedTime;

    public SendResource() {
    }

    public SendResource(Integer resourceId) {
        this.resourceId = resourceId;
    }

    public SendResource(Integer resourceId, String resourceName, String resourceType, String resourceLocation, String resourceProperty, Integer referrenceObjectId, String isDeleted, String createdBy, java.util.Date createdTime, String updatedBy, java.util.Date updatedTime) {
        this.resourceId = resourceId;
        this.resourceName = resourceName;
        this.resourceType = resourceType;
        this.resourceLocation = resourceLocation;
        this.resourceProperty = resourceProperty;
        this.referrenceObjectId = referrenceObjectId;
        this.isDeleted = isDeleted;
        this.createdBy = createdBy;
        this.createdTime = createdTime;
        this.updatedBy = updatedBy;
        this.updatedTime = updatedTime;
    }

    public Integer getResourceId() {
        return resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    public String getResourceName() {
        return resourceName;
    }

    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceLocation() {
        return resourceLocation;
    }

    public void setResourceLocation(String resourceLocation) {
        this.resourceLocation = resourceLocation;
    }

    public String getResourceProperty() {
        return resourceProperty;
    }

    public void setResourceProperty(String resourceProperty) {
        this.resourceProperty = resourceProperty;
    }

    public Integer getReferrenceObjectId() {
        return referrenceObjectId;
    }

    public void setReferrenceObjectId(Integer referrenceObjectId) {
        this.referrenceObjectId = referrenceObjectId;
    }

    public String getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public java.util.Date getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(java.util.Date createdTime) {
        this.createdTime = createdTime;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public java.util.Date getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(java.util.Date updatedTime) {
        this.updatedTime = updatedTime;
    }

}
